import test from 'node:test';
import assert from 'node:assert/strict';
import {Courtyard} from '../src/game.js';

function game(){const g=Object.create(Courtyard.prototype);g.keys=new Set();g.walls=[];g.world={w:1600,h:1088};g.camera={x:0,y:0};g.reset();g.walls=[];return g;}
function enemy(x,y,hp=2){return{x,y,r:14,hp,maxHp:hp,inv:0,clock:0,type:'slime',speed:0};}

test('walls and courtyard boundaries block movement',()=>{const g=game();g.walls=[{x:220,y:150,w:90,h:44}];g.player.x=205;g.player.y=175;g.move(g.player,10,0);assert.equal(g.player.x,205);assert.equal(g.blocked(20,100,13),true);assert.equal(g.blocked(100,100,13),false);});
test('only WASD moves the player',()=>{const g=game();g.keys.add('arrowright');g.update(.1);assert.equal(g.player.x,720);g.keys.clear();g.keys.add('d');g.update(.1);assert.ok(g.player.x>720);});
test('mouse aim attacks only enemies in the clicked direction',()=>{const g=game();g.player.x=200;g.player.y=250;g.enemies=[enemy(260,250,3),enemy(140,250,3)];g.waveTarget=2;g.setAim(400,250);g.queueAttack();g.update(.016);assert.equal(g.enemies[0].hp,1);assert.equal(g.enemies[1].hp,3);});
test('a wall blocks a mouse-directed attack',()=>{const g=game();g.player.x=205;g.player.y=175;g.walls=[{x:220,y:150,w:30,h:44}];g.enemies=[enemy(265,175)];g.waveTarget=1;g.setAim(300,175);g.queueAttack();g.update(.016);assert.equal(g.enemies[0].hp,2);});
test('clearing a wave advances to the next assault',()=>{const g=game();g.enemies=[enemy(760,520,1)];g.waveTarget=1;g.setAim(900,520);g.queueAttack();g.update(.016);assert.equal(g.waveKills,1);assert.ok(g.waveDelay>0);g.update(1.2);assert.equal(g.wave,2);assert.equal(g.enemies.length,13);});
test('holding the mouse repeats attacks after cooldown',()=>{const g=game();g.player.x=200;g.player.y=250;g.enemies=[enemy(270,250,8)];g.waveTarget=1;g.setAim(400,250);g.setAttackHeld(true);g.update(.016);const first=g.enemies[0].hp;for(let i=0;i<40;i++)g.update(.016);assert.ok(g.enemies[0].hp<first);});
test('cleave damages nearby enemies once and then enters cooldown',()=>{const g=game();g.player.x=200;g.player.y=250;g.enemies=[enemy(260,250,10),enemy(150,250,10),enemy(400,250,10)];g.waveTarget=3;assert.equal(g.useSkill('cleave'),true);g.update(.016);assert.ok(g.enemies[0].hp<10);assert.ok(g.enemies[1].hp<10);assert.equal(g.enemies[2].hp,10);assert.ok(g.skillCooldowns.cleave>4);assert.equal(g.useSkill('cleave'),false);});
test('dodge dashes in the held direction and starts cooldown',()=>{const g=game(),start=g.player.x;g.keys.add('d');assert.equal(g.useSkill('dodge'),true);g.update(.1);assert.ok(g.player.x>start+60);assert.ok(g.player.inv>0);assert.ok(g.skillCooldowns.dodge>2);assert.equal(g.useSkill('dodge'),false);});
test('dodge uses facing direction without movement input',()=>{const g=game(),start=g.player.y;g.player.face='up';g.useSkill('dodge');g.update(.1);assert.ok(g.player.y<start-60);});
test('dodge invulnerability prevents contact damage',()=>{const g=game(),hp=g.player.hp;g.keys.add('d');g.enemies=[enemy(g.player.x+66,g.player.y,20)];g.waveTarget=1;g.useSkill('dodge');g.update(.1);assert.equal(g.player.hp,hp);});
test('walls stop dodge movement',()=>{const g=game(),start=g.player.x;g.walls=[{x:start+20,y:g.player.y-30,w:40,h:60}];g.keys.add('d');g.useSkill('dodge');g.update(.1);assert.equal(g.player.x,start);assert.equal(g.player.dodge,null);});
test('battle cry pushes nearby enemies and starts its buff and cooldown',()=>{const g=game(),near=enemy(g.player.x+80,g.player.y,20),far=enemy(g.player.x+220,g.player.y,20);g.enemies=[near,far];g.waveTarget=2;assert.equal(g.useSkill('warCry'),true);g.update(.016);assert.ok(near.x>g.player.x+140);assert.equal(far.x,g.player.x+220);assert.ok(g.player.battleCry>5.9);assert.ok(g.skillCooldowns.warCry>11.9);assert.equal(g.useSkill('warCry'),false);});
test('battle cry increases basic and cleave damage by fifty percent',()=>{const normal=game(),buffed=game();normal.random=buffed.random=()=>1;normal.player.x=buffed.player.x=200;normal.player.y=buffed.player.y=250;normal.enemies=[enemy(260,250,20)];buffed.enemies=[enemy(260,250,20)];normal.waveTarget=buffed.waveTarget=1;normal.setAim(400,250);buffed.setAim(400,250);normal.queueAttack();buffed.player.battleCry=6;buffed.queueAttack();normal.update(.016);buffed.update(.016);assert.equal(20-normal.enemies[0].hp,2);assert.equal(20-buffed.enemies[0].hp,3);const cleave=game();cleave.player.x=200;cleave.player.y=250;cleave.player.battleCry=6;cleave.enemies=[enemy(260,250,20)];cleave.waveTarget=1;cleave.performCleave();assert.equal(20-cleave.enemies[0].hp,8);});
test('battle cry increases movement speed only while active',()=>{const normal=game(),buffed=game();normal.keys.add('d');buffed.keys.add('d');buffed.player.battleCry=6;normal.update(.1);buffed.update(.1);assert.ok(buffed.player.x-normal.player.x>3);assert.ok(buffed.player.x-normal.player.x<4);buffed.update(6);assert.equal(buffed.player.battleCry,0);});
test('cultists fire projectiles from range',()=>{const g=game();g.player.x=200;g.player.y=250;g.enemies=[{...enemy(400,250,4),type:'cultist',shot:0,speed:0}];g.waveTarget=1;g.update(.016);assert.equal(g.projectiles.length,1);});
test('screen aim converts through the scrolling camera',()=>{const g=game();g.camera={x:240,y:250};g.setAimScreen(480,270);assert.equal(g.player.aimX,720);assert.equal(g.player.aimY,520);});
test('mobile joystick supports analog movement and clamps its length',()=>{const g=game();g.setTouchMove(2,0);g.update(.1);assert.equal(g.touchMove.x,1);assert.equal(g.touchMove.y,0);assert.ok(g.player.x>720);g.setTouchMove(0,0);const x=g.player.x;g.update(.1);assert.equal(g.player.x,x);});
test('mobile attack automatically aims at the nearest living enemy',()=>{const g=game();g.player.x=200;g.player.y=250;g.enemies=[enemy(100,250,3),enemy(255,250,3)];g.waveTarget=2;g.setMobileAttackHeld(true);g.update(.016);assert.equal(g.enemies[0].hp,3);assert.equal(g.enemies[1].hp,1);g.setMobileAttackHeld(false);assert.equal(g.mobileAutoAim,false);});
test('equipped armor changes health and incoming damage',()=>{const g=game();g.inventory.items.push({id:'plate',slot:'armor',rarity:'rare',name:'갑옷',level:1,value:1,stats:{armor:3,health:10}});assert.equal(g.equip('plate'),true);assert.equal(g.player.maxHp,110);g.hurt(8);assert.equal(g.player.hp,105);});
test('the first defeated monster always drops equipment',()=>{const g=game();g.enemies=[];g.gainReward(enemy(700,500));assert.ok(g.drops.some(x=>x.type==='item'&&x.item));});
test('the boss guarantees two rare-or-better equipment drops',()=>{const g=game();g.random=()=>.5;g.enemies=[];g.gainReward({...enemy(700,500,24),type:'brute'});const items=g.drops.filter(drop=>drop.type==='item');assert.equal(items.length,2);assert.ok(items.every(drop=>['rare','legendary'].includes(drop.item.rarity)));assert.notEqual(items[0].item.id,items[1].item.id);});
test('legendary boss loot creates a visible announcement',()=>{const g=game();g.random=()=>.1;g.enemies=[];g.gainReward({...enemy(700,500,24),type:'brute'});assert.ok(g.drops.filter(drop=>drop.type==='item').every(drop=>drop.item.rarity==='legendary'));assert.ok(g.texts.some(text=>text.text==='전설 전리품!'));assert.ok(g.particles.length>=48);});
test('upgrade detection compares a drop with the equipped item in the same slot',()=>{const g=game(),equipped={id:'old',slot:'weapon',rarity:'common',name:'낡은 검',level:1,value:1,stats:{damage:1}},strong={id:'new',slot:'weapon',rarity:'rare',name:'강한 검',level:2,value:2,stats:{damage:4}},weak={...strong,id:'weak',level:1,stats:{damage:0}};g.inventory.items=[equipped];g.inventory.equipment.weapon='old';assert.equal(g.isUpgrade(strong),true);assert.equal(g.isUpgrade(weak),false);assert.equal(g.isUpgrade({...strong,slot:'ring'}),true);});
test('cultists use a richer reward profile than common monsters',()=>{const common=game(),elite=game();common.random=()=>.25;elite.random=()=>.25;common.kills=1;elite.kills=1;common.gainReward({...enemy(700,500),type:'slime'});elite.gainReward({...enemy(700,500),type:'cultist'});assert.equal(common.drops.some(drop=>drop.type==='item'),false);assert.equal(elite.drops.some(drop=>drop.type==='item'),true);assert.ok(elite.gold>common.gold);assert.ok(elite.xp>common.xp);});
test('a full bag keeps ground loot and shows one clear warning',()=>{const g=game(),base={slot:'ring',rarity:'common',name:'반지',level:1,value:1,stats:{crit:1}};g.inventory.limit=1;g.inventory.items=[{...base,id:'held'}];g.drops=[{x:g.player.x,y:g.player.y,life:60,type:'item',item:{...base,id:'ground'}}];g.update(.016);assert.equal(g.drops.length,1);assert.equal(g.drops[0].warned,true);assert.ok(g.texts.some(text=>text.text==='가방이 가득 찼습니다'));const warnings=g.texts.length;g.update(.016);assert.equal(g.texts.length,warnings);});
test('pause freezes gameplay',()=>{const g=game();g.paused=true;g.keys.add('d');g.update(1);assert.equal(g.player.x,720);assert.equal(g.time,0);});
