import test from 'node:test';
import assert from 'node:assert/strict';
import {addItem,bonuses,carriedItems,createInventory,discardItem,equipItem,generateItem,itemIconKey,ITEM_ICON_PATHS,loadInventory,saveInventory,sortInventory,SLOTS,unequipSlot} from '../src/items.js';

const sequence=(...values)=>{let i=0;return()=>values[i++%values.length];};
test('generated loot has a valid slot, rarity, icon and combat stats',()=>{for(let i=0;i<Object.keys(SLOTS).length;i++){const item=generateItem({wave:2,rng:sequence((i+.01)/Object.keys(SLOTS).length,.9,.5,.2,.1,.3),id:`item-${i}`});assert.ok(SLOTS[item.slot]);assert.ok(item.name);assert.ok(ITEM_ICON_PATHS[itemIconKey(item)]);assert.ok(Object.values(item.stats).some(x=>x>0));}});
test('boss loot is always rare or legendary',()=>{const item=generateItem({wave:3,boss:true,rng:sequence(.5,.2,.5,.5,.5),id:'boss'});assert.ok(['rare','legendary'].includes(item.rarity));});
test('equipped items contribute bonuses and cannot be discarded',()=>{const bag=createInventory(),item={id:'sword',slot:'weapon',rarity:'rare',name:'검',level:1,value:1,stats:{damage:4,crit:3}};assert.equal(addItem(bag,item),true);assert.equal(equipItem(bag,'sword'),true);assert.deepEqual(bonuses(bag),{damage:4,armor:0,health:0,crit:3,speed:0});assert.equal(discardItem(bag,'sword'),false);});
test('discarding a carried item removes it and frees bag capacity',()=>{const bag=createInventory(1),item={id:'ring',slot:'ring',rarity:'common',name:'반지',level:1,stats:{crit:1}};assert.equal(addItem(bag,item),true);assert.equal(discardItem(bag,'ring'),true);assert.equal(carriedItems(bag).length,0);assert.equal(addItem(bag,{...item,id:'ring-2'}),true);});
test('inventory capacity is enforced',()=>{const bag=createInventory(1),item={slot:'ring',rarity:'common',name:'반지',level:1,value:1,stats:{crit:1}};assert.equal(addItem(bag,{...item,id:'1'}),true);assert.equal(addItem(bag,{...item,id:'2'}),false);});
test('equipped items do not occupy bag slots',()=>{const bag=createInventory(1),sword={id:'sword',slot:'weapon',rarity:'common',level:1,name:'검',stats:{damage:1}};assert.equal(addItem(bag,sword),true);assert.equal(equipItem(bag,'sword'),true);assert.equal(addItem(bag,{id:'ring',slot:'ring',rarity:'common',level:1,name:'반지',stats:{crit:1}}),true);assert.equal(carriedItems(bag).length,1);assert.equal(unequipSlot(bag,'weapon'),false);});
test('inventory sorting groups carried items by slot rarity and level',()=>{const bag=createInventory();bag.items.push({id:'a',slot:'armor',rarity:'common',level:1,name:'갑옷'},{id:'b',slot:'weapon',rarity:'common',level:1,name:'검'},{id:'c',slot:'weapon',rarity:'rare',level:2,name:'희귀 검'});sortInventory(bag);assert.deepEqual(bag.items.map(x=>x.id),['c','b','a']);});
test('inventory round-trips through storage',()=>{const data=new Map(),storage={setItem:(k,v)=>data.set(k,v),getItem:k=>data.get(k)};const bag=createInventory(),item={id:'saved',slot:'charm',rarity:'rare',name:'부적',level:2,value:3,stats:{crit:2}};assert.equal(addItem(bag,item),true);assert.equal(saveInventory(bag,storage),true);assert.equal(loadInventory(storage).items[0].id,'saved');});
test('invalid and duplicate saved items are removed and equipment references are repaired',()=>{const valid={id:'valid',slot:'weapon',rarity:'rare',name:'검',level:2,value:4,stats:{damage:3}},data={version:1,limit:999,items:[valid,{...valid},{id:'bad',slot:'cape',rarity:'rare',name:'망토',level:1,stats:{armor:2}},{id:'nan',slot:'ring',rarity:'common',name:'반지',level:1,stats:{crit:NaN}}],equipment:{weapon:'valid',armor:'valid',ring:'missing'}},storage={getItem:()=>JSON.stringify(data)};const bag=loadInventory(storage);assert.equal(bag.limit,20);assert.deepEqual(bag.items.map(item=>item.id),['valid']);assert.equal(bag.equipment.weapon,'valid');assert.equal(bag.equipment.armor,null);assert.equal(bag.equipment.ring,null);});
test('overfilled saved bags are trimmed without losing equipped items',()=>{const ring=i=>({id:`ring-${i}`,slot:'ring',rarity:'common',name:'반지',level:1,value:1,stats:{crit:1}}),weapon={id:'equipped',slot:'weapon',rarity:'rare',name:'검',level:2,value:4,stats:{damage:3}},data={version:1,limit:2,items:[ring(1),ring(2),ring(3),weapon],equipment:{weapon:'equipped'}},storage={getItem:()=>JSON.stringify(data)};const bag=loadInventory(storage);assert.deepEqual(bag.items.map(item=>item.id),['ring-1','ring-2','equipped']);assert.equal(carriedItems(bag).length,2);assert.equal(bag.equipment.weapon,'equipped');});
test('invalid or duplicate items cannot enter the inventory',()=>{const bag=createInventory(),valid={id:'valid',slot:'weapon',rarity:'common',name:'검',level:1,value:1,stats:{damage:1}};assert.equal(addItem(bag,{id:'bad'}),false);assert.equal(addItem(bag,valid),true);assert.equal(addItem(bag,valid),false);assert.equal(equipItem(bag,'missing'),false);});
