import {Courtyard} from './game.js?v=10';
import {ITEM_ICON_PATHS,itemIconKey} from './items.js?v=3';
const $=id=>document.getElementById(id),overlay=$('overlay'),canvas=$('game'),bag=$('inventory');let game,lastState,selectedItemId=null,bagSignature='',resumeAfterBag=false,lastSnapshot;
function show(title,message,label){$('title').textContent=title;$('message').textContent=message;$('start').textContent=label;overlay.hidden=false;}
function point(event){const r=canvas.getBoundingClientRect();return{x:(event.clientX-r.left)*canvas.width/r.width,y:(event.clientY-r.top)*canvas.height/r.height};}
const rarityColor={common:'#b8b7ae',magic:'#5aa8e8',rare:'#e3c151',legendary:'#e8793e'},rarityName={common:'일반',magic:'마법',rare:'희귀',legendary:'전설'},slotIcon={weapon:'⚔',armor:'♜',charm:'◆'},statName={damage:'공격력',armor:'방어력',health:'최대 체력',crit:'치명타',speed:'이동 속도'},iconPath=item=>ITEM_ICON_PATHS[itemIconKey(item)];
function renderBag(state,force=false){
 if(!state?.inventory)return;lastSnapshot=state;const inv=state.inventory,sig=JSON.stringify([inv,state.gear,selectedItemId]);if(!force&&sig===bagSignature)return;bagSignature=sig;$('bag-count').textContent=`${inv.items.length} / ${inv.limit}`;$('bag-stats').replaceChildren(...Object.entries(state.gear).map(([k,v])=>{const span=document.createElement('span');span.textContent=`${statName[k]} `;const b=document.createElement('b');b.textContent=`+${v}${k==='crit'||k==='speed'?'%':''}`;span.append(b);return span;}));
 for(const button of bag.querySelectorAll('[data-slot]')){const id=inv.equipment[button.dataset.slot],item=inv.items.find(x=>x.id===id),visual=button.querySelector('.gear-icon');button.querySelector('strong').textContent=item?.name||'비어 있음';visual.replaceChildren();visual.textContent=item?'':slotIcon[button.dataset.slot];if(item){const img=document.createElement('img');img.src=iconPath(item);img.alt='';visual.append(img);}button.style.borderColor=item?rarityColor[item.rarity]:'';}
 const list=$('item-list');list.replaceChildren();for(const item of inv.items){const button=document.createElement('button');button.className=`item-card${item.id===selectedItemId?' selected':''}${Object.values(inv.equipment).includes(item.id)?' equipped':''}`;button.style.setProperty('--rarity',rarityColor[item.rarity]);button.dataset.item=item.id;button.title=item.name;const img=document.createElement('img');img.src=iconPath(item);img.alt=item.name;const level=document.createElement('em');level.textContent=`LV ${item.level}`;button.append(img,level);list.append(button);}
 const detail=$('item-detail'),item=inv.items.find(x=>x.id===selectedItemId);detail.replaceChildren();if(!item){const p=document.createElement('p');p.textContent=inv.items.length?'아이템을 선택하면 현재 장비와 비교할 수 있습니다.':'몬스터를 처치하면 장비가 이곳에 보관됩니다.';detail.append(p);return;}detail.style.setProperty('--rarity',rarityColor[item.rarity]);const preview=document.createElement('img');preview.className='item-preview';preview.src=iconPath(item);preview.alt='';const copy=document.createElement('div');copy.className='item-copy';const h=document.createElement('h4');h.textContent=item.name;const meta=document.createElement('small');meta.textContent=`${rarityName[item.rarity]} · ${item.level}레벨`;const ul=document.createElement('ul'),equipped=inv.items.find(x=>x.id===inv.equipment[item.slot]);for(const [key,value] of Object.entries(item.stats)){const li=document.createElement('li'),delta=value-(equipped?.stats[key]||0);li.textContent=`${statName[key]} +${value}${key==='crit'||key==='speed'?'%':''}${equipped&&delta!==0?` (${delta>0?'+':''}${delta})`:''}`;ul.append(li);}copy.append(h,meta,ul);const actions=document.createElement('div');actions.className='item-actions';const isEquipped=inv.equipment[item.slot]===item.id,equip=document.createElement('button');equip.textContent=isEquipped?'장착 해제':'장착';equip.dataset.action=isEquipped?'unequip':'equip';equip.dataset.id=item.id;equip.dataset.slot=item.slot;const discard=document.createElement('button');discard.textContent='버리기';discard.className='discard';discard.dataset.action='discard';discard.dataset.id=item.id;discard.disabled=isEquipped;actions.append(equip,discard);detail.append(preview,copy,actions);
}
function toggleBag(open=!bag.hidden){if(!game)return;if(open){resumeAfterBag=!game.paused&&game.state==='playing';game.paused=true;game.keys.clear();game.setAttackHeld(false);bag.hidden=false;renderBag(lastSnapshot,true);}else{bag.hidden=true;if(resumeAfterBag&&game.state==='playing')game.paused=false;resumeAfterBag=false;canvas.focus();}}
async function boot(){
 try{
  const response=await fetch('assets/manifest.json?v=6');if(!response.ok)throw Error('asset manifest');const manifest=await response.json(),images={};
  await Promise.all([...Object.entries(manifest).filter(([,v])=>v.src).map(([key,v])=>[key,v.src]),...Object.entries(ITEM_ICON_PATHS).map(([key,src])=>[`item-${key}`,src])].map(async([key,src])=>{const img=new Image();img.src=src;await img.decode();images[key]=img;}));
  game=new Courtyard(canvas,manifest,images,s=>{
   $('health').textContent=`${s.hp} / ${s.maxHp}`;$('healthbar').style.width=`${100*s.hp/s.maxHp}%`;$('score').textContent=`${s.kills} / ${s.total}`;$('wave').textContent=s.wave;$('level').textContent=s.level;$('gold').textContent=s.gold;$('xpbar').style.width=`${100*s.xp/s.xpNext}%`;
   renderBag(s);
   if(s.state!==lastState&&s.state==='won')show('공성 시험 완료','세 번의 습격을 모두 막아냈습니다. 더 빠른 기록으로 다시 도전해보세요.','다시 플레이');
   if(s.state!==lastState&&s.state==='lost')show('잿빛 안뜰 함락','거리를 벌리며 마우스로 적을 조준해 공격하세요.','다시 도전');lastState=s.state;
  });
  game.paused=true;$('start').disabled=false;show('잿빛 공성 시험','WASD로 이동하고 마우스로 조준하세요. 클릭하면 커서 방향으로 검을 휘두릅니다.','전투 시작');
 }catch(e){show('에셋을 불러오지 못했어요','페이지를 새로고침해서 다시 시도해주세요.','새로고침');$('start').disabled=false;$('start').onclick=()=>location.reload();console.error(e);}
}
$('start').onclick=()=>{if(!game)return;if(game.state!=='playing')game.reset();game.paused=false;game.keys.clear();lastState='playing';overlay.hidden=true;$('pause').textContent='Ⅱ';canvas.focus();};
$('pause').onclick=()=>{if(!game||game.state!=='playing')return;game.paused=!game.paused;game.keys.clear();$('pause').textContent=game.paused?'▶':'Ⅱ';if(game.paused)show('전투 일시정지','준비되면 공성 시험으로 돌아오세요.','계속하기');else overlay.hidden=true;};
$('bag').onclick=()=>toggleBag(bag.hidden);$('close-bag').onclick=()=>toggleBag(false);bag.addEventListener('click',e=>{const itemButton=e.target.closest('[data-item]');if(itemButton){selectedItemId=itemButton.dataset.item;renderBag(lastSnapshot,true);return;}const action=e.target.closest('[data-action]');if(action&&game){if(action.dataset.action==='equip')game.equip(action.dataset.id);if(action.dataset.action==='unequip')game.unequip(action.dataset.slot);if(action.dataset.action==='discard'){game.discard(action.dataset.id);selectedItemId=null;}renderBag(lastSnapshot,true);return;}const slot=e.target.closest('[data-slot]');if(slot&&game){game.unequip(slot.dataset.slot);renderBag(lastSnapshot,true);}});window.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='i'){e.preventDefault();toggleBag(bag.hidden);}if(e.key==='Escape'&&!bag.hidden)toggleBag(false);});
canvas.addEventListener('pointermove',e=>{if(game){const p=point(e);game.setAimScreen(p.x,p.y);}});canvas.addEventListener('pointerdown',e=>{if(!game||game.paused||e.button!==0)return;e.preventDefault();const p=point(e);game.setAimScreen(p.x,p.y);game.setAttackHeld(true);canvas.setPointerCapture(e.pointerId);canvas.focus();});const stopAttack=()=>game?.setAttackHeld(false);canvas.addEventListener('pointerup',stopAttack);canvas.addEventListener('pointercancel',stopAttack);canvas.addEventListener('lostpointercapture',stopAttack);canvas.addEventListener('contextmenu',e=>e.preventDefault());
for(const button of document.querySelectorAll('[data-key]')){button.onpointerdown=e=>{e.preventDefault();if(!game||game.paused)return;button.setPointerCapture(e.pointerId);game.keys.add(button.dataset.key);};const release=()=>game?.keys.delete(button.dataset.key);button.onpointerup=release;button.onpointercancel=release;button.onlostpointercapture=release;}
const touchAttack=document.querySelector('[data-action="attack"]');touchAttack.onpointerdown=e=>{e.preventDefault();if(game&&!game.paused)game.setAttackHeld(true);};touchAttack.onpointerup=touchAttack.onpointercancel=()=>game?.setAttackHeld(false);document.addEventListener('visibilitychange',()=>{if(document.hidden&&game&&game.state==='playing'){game.paused=true;game.keys.clear();game.setAttackHeld(false);show('전투 일시정지','준비되면 계속 플레이하세요.','계속하기');}});boot();
