import {Courtyard} from './game.js?v=13';
import {ITEM_ICON_PATHS,itemIconKey,SLOTS} from './items.js?v=7';
const $=id=>document.getElementById(id),overlay=$('overlay'),canvas=$('game'),bag=$('inventory'),bagNotice=$('inventory-notice');let game,lastState,selectedItemId=null,bagSignature='',resumeAfterBag=false,lastSnapshot,noticeTimer;
function show(title,message,label){$('title').textContent=title;$('message').textContent=message;$('start').textContent=label;overlay.hidden=false;}
function notifyBag(message){clearTimeout(noticeTimer);bagNotice.textContent=message;bagNotice.hidden=false;noticeTimer=setTimeout(()=>bagNotice.hidden=true,2400);}
function point(event){const r=canvas.getBoundingClientRect();return{x:(event.clientX-r.left)*canvas.width/r.width,y:(event.clientY-r.top)*canvas.height/r.height};}
const rarityColor={common:'#b8b7ae',magic:'#5aa8e8',rare:'#e3c151',legendary:'#e8793e'},rarityName={common:'일반',magic:'마법',rare:'희귀',legendary:'전설'},slotIcon=Object.fromEntries(Object.entries(SLOTS).map(([key,value])=>[key,value.icon])),statName={damage:'공격력',armor:'방어력',health:'최대 체력',crit:'치명타',speed:'이동 속도'},iconPath=item=>ITEM_ICON_PATHS[itemIconKey(item)],itemPower=item=>item?Math.round(item.level*8+(item.stats.damage||0)*5+(item.stats.armor||0)*4+(item.stats.health||0)*.3+(item.stats.crit||0)*1.5+(item.stats.speed||0)):0;
function loadShowcase(){if(!new URLSearchParams(location.search).has('showcase'))return false;const items=[{id:'demo-sword',slot:'weapon',rarity:'rare',level:4,name:'맹공의 파수꾼의 검 · 학살',icon:'royal-flame-sword',stats:{damage:7,crit:5},affixes:[{id:'assault',label:'맹공의'},{id:'slaughter',label:'학살'}],value:48},{id:'demo-shield',slot:'shield',rarity:'rare',level:4,name:'기사단의 망자 방패',icon:'steel-shield',stats:{armor:5,health:16},value:46},{id:'demo-helmet',slot:'helmet',rarity:'legendary',level:5,name:'불멸자의 핏빛 갈기 투구',icon:'knight-helmet',stats:{armor:4,crit:4},value:79},{id:'demo-armor',slot:'armor',rarity:'legendary',level:5,name:'불멸자의 수호자 판금',icon:'royal-plate',stats:{armor:6,health:34},value:91},{id:'demo-gloves',slot:'gloves',rarity:'magic',level:3,name:'날카로운 성채 건틀릿',icon:'armored-gloves',stats:{damage:2,crit:4},value:31},{id:'demo-boots',slot:'boots',rarity:'rare',level:4,name:'황혼의 철기병 장화',icon:'plated-boots',stats:{armor:3,speed:8},value:44},{id:'demo-belt',slot:'belt',rarity:'magic',level:3,name:'견고한 용병 허리띠',icon:'utility-belt',stats:{health:18,armor:2},value:33},{id:'demo-amulet',slot:'amulet',rarity:'rare',level:4,name:'핏빛 서약 목걸이',icon:'ruby-amulet',stats:{damage:2,crit:7},value:55},{id:'demo-ring',slot:'ring',rarity:'magic',level:3,name:'왕실 인장 반지',icon:'gold-ring',stats:{crit:5,speed:3},value:36},{id:'demo-charm',slot:'charm',rarity:'rare',level:4,name:'황혼의 핏빛 룬',icon:'blood-rune',stats:{crit:9,speed:7,damage:1},value:52},{id:'demo-axe',slot:'weapon',rarity:'magic',level:3,name:'맹공의 묘지기의 도끼',icon:'gravekeeper-axe',stats:{damage:5,crit:3},affixes:[{id:'assault',label:'맹공의'}],value:29},{id:'demo-mail',slot:'armor',rarity:'common',level:2,name:'해진 사슬갑옷',icon:'torn-chainmail',stats:{armor:2,health:10},value:13}];game.inventory={version:1,limit:20,items,equipment:{weapon:'demo-sword',shield:'demo-shield',helmet:'demo-helmet',armor:'demo-armor',gloves:'demo-gloves',boots:'demo-boots',belt:'demo-belt',amulet:'demo-amulet',ring:'demo-ring',charm:'demo-charm'}};selectedItemId='demo-axe';game.recalculateStats();return true;}
function renderBag(state,force=false){
 if(!state?.inventory)return;lastSnapshot=state;const inv=state.inventory,sig=JSON.stringify([inv,state.gear,selectedItemId]);if(!force&&sig===bagSignature)return;bagSignature=sig;$('bag-stats').replaceChildren(...Object.entries(state.gear).map(([k,v])=>{const span=document.createElement('span');span.textContent=`${statName[k]} `;const b=document.createElement('b');b.textContent=`+${v}${k==='crit'||k==='speed'?'%':''}`;span.append(b);return span;}));
 for(const button of bag.querySelectorAll('.equip-slot[data-slot]')){const slot=button.dataset.slot,id=inv.equipment[slot],item=inv.items.find(x=>x.id===id),visual=button.querySelector('.gear-icon');button.querySelector('strong').textContent=item?.name||'비어 있음';button.setAttribute('aria-label',`${SLOTS[slot].label}: ${item?.name||'비어 있음'}`);button.title=item?`${SLOTS[slot].label} · ${item.name}`:`빈 ${SLOTS[slot].label} 슬롯`;button.classList.toggle('filled',!!item);visual.replaceChildren();visual.textContent=item?'':slotIcon[slot];if(item){const img=document.createElement('img');img.src=iconPath(item);img.alt='';visual.append(img);}button.style.borderColor=item?rarityColor[item.rarity]:'';}
 const equippedIdSet=new Set(Object.values(inv.equipment).filter(Boolean)),carried=inv.items.filter(item=>!equippedIdSet.has(item.id));$('bag-count').textContent=`${carried.length} / ${inv.limit}`;const list=$('item-list');list.replaceChildren();let usedCells=0;for(const item of carried){const button=document.createElement('button');button.className=`item-card slot-${item.slot}${item.id===selectedItemId?' selected':''}`;button.style.setProperty('--rarity',rarityColor[item.rarity]);button.dataset.item=item.id;button.title=item.name;const img=document.createElement('img');img.src=iconPath(item);img.alt=item.name;const level=document.createElement('em');level.textContent=`Lv.${item.level}`;button.append(img,level);list.append(button);usedCells++;}for(let i=usedCells;i<inv.limit;i++){const empty=document.createElement('i');empty.className='empty-cell';empty.setAttribute('aria-hidden','true');list.append(empty);}
 const detail=$('item-detail'),item=inv.items.find(x=>x.id===selectedItemId);detail.replaceChildren();if(!item){const p=document.createElement('p');p.textContent=carried.length?'가방에서 아이템을 선택하면 현재 장비와 비교합니다.':'가방이 비어 있습니다. 몬스터를 처치해 전리품을 획득하세요.';detail.append(p);return;}detail.style.setProperty('--rarity',rarityColor[item.rarity]);const preview=document.createElement('img');preview.className='item-preview';preview.src=iconPath(item);preview.alt='';const copy=document.createElement('div');copy.className='item-copy';const h=document.createElement('h4');h.textContent=item.name;const ul=document.createElement('ul'),equipped=inv.items.find(x=>x.id===inv.equipment[item.slot]),power=itemPower(item),powerDelta=equipped?.id!==item.id?power-itemPower(equipped):0;const meta=document.createElement('small');meta.textContent=`아이템 파워 ${power}  ·  ${rarityName[item.rarity]} ${SLOTS[item.slot].label}  ·  레벨 ${item.level}`;if(equipped&&powerDelta){const delta=document.createElement('em');delta.className=powerDelta>0?'up':'down';delta.textContent=` ${powerDelta>0?'▲':'▼'} ${Math.abs(powerDelta)}`;meta.append(delta);}const affixes=document.createElement('em');affixes.className='affixes';affixes.textContent=` · 옵션 ${item.affixes?.length?item.affixes.map(affix=>affix.label).join('·'):'없음'}`;meta.append(affixes);const comparison=document.createElement('p');comparison.className='comparison';comparison.textContent=equipped?.id===item.id?'현재 장착 중':equipped?`현재 장비 · ${equipped.name} · 파워 ${itemPower(equipped)}`:`현재 장비 · 비어 있음`;for(const key of new Set([...Object.keys(item.stats),...Object.keys(equipped?.stats||{})])){const value=item.stats[key]||0,li=document.createElement('li'),delta=value-(equipped?.stats[key]||0),label=document.createElement('span'),amount=document.createElement('b');label.textContent=statName[key];amount.textContent=`+${value}${key==='crit'||key==='speed'?'%':''}`;li.append(label,amount);if(equipped&&equipped.id!==item.id&&delta!==0){const compare=document.createElement('em');compare.className=delta>0?'up':'down';compare.textContent=`${delta>0?'▲':'▼'} ${Math.abs(delta)}`;li.append(compare);}ul.append(li);}const value=document.createElement('footer');value.innerHTML=`<span>판매 가격</span><b>◆ ${item.value}</b>`;copy.append(h,meta,comparison,ul,value);const actions=document.createElement('div');actions.className='item-actions';const isEquipped=inv.equipment[item.slot]===item.id,equip=document.createElement('button');equip.textContent=isEquipped?'장착 해제':'장착';equip.dataset.action=isEquipped?'unequip':'equip';equip.dataset.id=item.id;equip.dataset.slot=item.slot;const discard=document.createElement('button');discard.textContent='버리기';discard.className='discard';discard.dataset.action='discard';discard.dataset.id=item.id;discard.disabled=isEquipped;actions.append(equip,discard);detail.append(preview,copy,actions);
}
function refreshBag(){if(!game||!lastSnapshot)return;lastSnapshot={...lastSnapshot,inventory:game.inventory,gear:game.gear};bagSignature='';renderBag(lastSnapshot,true);}
function toggleBag(open=!bag.hidden){if(!game)return;if(open){resumeAfterBag=!game.paused&&game.state==='playing';game.paused=true;game.keys.clear();game.setTouchMove(0,0);game.setMobileAttackHeld(false);bag.hidden=false;renderBag(lastSnapshot,true);}else{bag.hidden=true;if(resumeAfterBag&&game.state==='playing')game.paused=false;resumeAfterBag=false;canvas.focus();}}
async function boot(){
 try{
  const response=await fetch('assets/manifest.json?v=6');if(!response.ok)throw Error('asset manifest');const manifest=await response.json(),images={};
  await Promise.all([...Object.entries(manifest).filter(([,v])=>v.src).map(([key,v])=>[key,v.src]),...Object.entries(ITEM_ICON_PATHS).map(([key,src])=>[`item-${key}`,src])].map(async([key,src])=>{const img=new Image();img.src=src;await img.decode();images[key]=img;}));
  game=new Courtyard(canvas,manifest,images,s=>{
   $('health').textContent=`${s.hp} / ${s.maxHp}`;$('healthbar').style.width=`${100*s.hp/s.maxHp}%`;$('score').textContent=`${s.kills} / ${s.total}`;$('wave').textContent=s.wave;$('level').textContent=s.level;$('gold').textContent=s.gold;$('xpbar').style.width=`${100*s.xp/s.xpNext}%`;const cleave=s.skills?.cleave||0,cleaveButton=$('cleave-skill');cleaveButton.classList.toggle('cooling',cleave>0);$('cleave-cooldown').textContent=cleave>0?cleave.toFixed(1):'';
   renderBag(s);
   if(s.state!==lastState&&s.state==='won')show('공성 시험 완료','세 번의 습격을 모두 막아냈습니다. 더 빠른 기록으로 다시 도전해보세요.','다시 플레이');
   if(s.state!==lastState&&s.state==='lost')show('잿빛 안뜰 함락','거리를 벌리며 마우스로 적을 조준해 공격하세요.','다시 도전');lastState=s.state;
  });
  const showcase=loadShowcase();game.paused=true;$('start').disabled=false;if(showcase){bag.hidden=false;overlay.hidden=true;}else show('잿빛 공성 시험','PC는 WASD와 마우스, 모바일은 조이스틱과 공격 버튼으로 전투합니다.','전투 시작');
 }catch(e){show('에셋을 불러오지 못했어요','페이지를 새로고침해서 다시 시도해주세요.','새로고침');$('start').disabled=false;$('start').onclick=()=>location.reload();console.error(e);}
}
$('start').onclick=()=>{if(!game)return;if(game.state!=='playing')game.reset();game.paused=false;game.keys.clear();lastState='playing';overlay.hidden=true;$('pause').textContent='Ⅱ';canvas.focus();};
$('pause').onclick=()=>{if(!game||game.state!=='playing')return;game.paused=!game.paused;game.keys.clear();$('pause').textContent=game.paused?'▶':'Ⅱ';if(game.paused)show('전투 일시정지','준비되면 공성 시험으로 돌아오세요.','계속하기');else overlay.hidden=true;};
$('bag').onclick=()=>toggleBag(bag.hidden);$('close-bag').onclick=()=>toggleBag(false);$('sort-bag').onclick=()=>{if(game){game.sortInventory();refreshBag();}};bag.addEventListener('click',e=>{const action=e.target.closest('[data-action]');if(action&&game){if(action.dataset.action==='equip'&&!game.equip(action.dataset.id))notifyBag('이 아이템을 장착할 수 없습니다.');if(action.dataset.action==='unequip'&&!game.unequip(action.dataset.slot))notifyBag('가방이 가득 차 장착을 해제할 수 없습니다.');if(action.dataset.action==='discard'){if(game.discard(action.dataset.id))selectedItemId=null;else notifyBag('장착 중인 아이템은 버릴 수 없습니다.');}refreshBag();return;}const itemButton=e.target.closest('[data-item]');if(itemButton){selectedItemId=itemButton.dataset.item;renderBag(lastSnapshot,true);return;}const slot=e.target.closest('[data-slot]');if(slot){selectedItemId=game?.inventory.equipment[slot.dataset.slot]||null;renderBag(lastSnapshot,true);}});bag.addEventListener('contextmenu',e=>{const itemButton=e.target.closest('[data-item]'),slot=e.target.closest('[data-slot]');if(!itemButton&&!slot)return;e.preventDefault();if(itemButton&&game){const id=itemButton.dataset.item;if(e.ctrlKey||e.metaKey){if(game.discard(id)&&selectedItemId===id)selectedItemId=null;}else if(!game.equip(id))notifyBag('이 아이템을 장착할 수 없습니다.');}else if(slot&&game&&!game.unequip(slot.dataset.slot))notifyBag('가방이 가득 차 장착을 해제할 수 없습니다.');refreshBag();});window.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='i'){e.preventDefault();toggleBag(bag.hidden);}if(e.key==='Escape'&&!bag.hidden)toggleBag(false);});
$('cleave-skill').onclick=()=>game?.useSkill('cleave');
canvas.addEventListener('pointermove',e=>{if(game){const p=point(e);game.setAimScreen(p.x,p.y);}});canvas.addEventListener('pointerdown',e=>{if(!game||game.paused||e.button!==0)return;e.preventDefault();const p=point(e);game.setAimScreen(p.x,p.y);game.setAttackHeld(true);canvas.setPointerCapture(e.pointerId);canvas.focus();});const stopAttack=()=>game?.setAttackHeld(false);canvas.addEventListener('pointerup',stopAttack);canvas.addEventListener('pointercancel',stopAttack);canvas.addEventListener('lostpointercapture',stopAttack);canvas.addEventListener('contextmenu',e=>e.preventDefault());
const joystick=$('joystick'),joystickKnob=$('joystick-knob'),touchControls=joystick.closest('.touch');let joystickPointer=null;
function updateJoystick(e){const rect=joystick.getBoundingClientRect(),radius=rect.width*.32,dx=e.clientX-(rect.left+rect.width/2),dy=e.clientY-(rect.top+rect.height/2),distance=Math.hypot(dx,dy),scale=distance>radius?radius/distance:1,x=dx*scale,y=dy*scale;joystickKnob.style.transform=`translate(${x}px, ${y}px)`;game?.setTouchMove(x/radius,y/radius);}
function releaseJoystick(e){if(joystickPointer!==null&&e?.pointerId!==undefined&&e.pointerId!==joystickPointer)return;joystickPointer=null;joystickKnob.style.transform='translate(0, 0)';touchControls.classList.remove('active');game?.setTouchMove(0,0);}
joystick.onpointerdown=e=>{e.preventDefault();if(!game||game.paused)return;joystickPointer=e.pointerId;joystick.setPointerCapture(e.pointerId);touchControls.classList.add('active');updateJoystick(e);};joystick.onpointermove=e=>{if(e.pointerId===joystickPointer)updateJoystick(e);};joystick.onpointerup=joystick.onpointercancel=joystick.onlostpointercapture=releaseJoystick;
const touchAttack=document.querySelector('[data-action="attack"]');touchAttack.onpointerdown=e=>{e.preventDefault();if(game&&!game.paused){touchAttack.setPointerCapture(e.pointerId);game.setMobileAttackHeld(true);}};const releaseAttack=()=>game?.setMobileAttackHeld(false);touchAttack.onpointerup=touchAttack.onpointercancel=touchAttack.onlostpointercapture=releaseAttack;
document.querySelector('[data-action="cleave"]').onpointerdown=e=>{e.preventDefault();game?.useSkill('cleave');};document.addEventListener('visibilitychange',()=>{if(document.hidden&&game&&game.state==='playing'){game.paused=true;game.keys.clear();releaseJoystick();game.setMobileAttackHeld(false);show('전투 일시정지','준비되면 계속 플레이하세요.','계속하기');}});boot();
